expected-from-site-level-config:
  condor_host_execution_id: {type: str(), required: true, use_default: false, description: "The execution_id of the lightweight_component that this container should submit to."}
  condor_host_port: {type: int(), required: true, use_default: true, description: "The port at which the condor daemons for the condor host are reachable"}
